apiVersion: v1
data:
  ENABLE_FEATURE: the stable feature that belongs in prod
kind: ConfigMap
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 088f723b-5c8a-483e-8ea9-769f55a4653a
  name: fancy-features-gtgb94tk65
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 088f723b-5c8a-483e-8ea9-769f55a4653a
  name: kubecamp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: kubecamp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 088f723b-5c8a-483e-8ea9-769f55a4653a
  name: kubecamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecamp
  template:
    metadata:
      labels:
        app: kubecamp
        app.kubernetes.io/managed-by: skaffold
        skaffold.dev/run-id: 088f723b-5c8a-483e-8ea9-769f55a4653a
    spec:
      containers:
      - env:
        - name: ENABLE_FEATURE
          valueFrom:
            configMapKeyRef:
              key: ENABLE_FEATURE
              name: fancy-features-gtgb94tk65
        image: gcr.io/agmsb-k8s/kubecamp-app:ef5dea6@sha256:02c8f7ae18838c0b976cce28df43bbb80ef94b49b034416717d8fcf1ce743900
        imagePullPolicy: IfNotPresent
        name: kubecamp-app
        ports:
        - containerPort: 5000
