apiVersion: v1
data:
  ENABLE_FEATURE: the stable feature that belongs in prod
kind: ConfigMap
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: b907d978-68be-4364-8db4-aa48e940f712
  name: fancy-features-gtgb94tk65
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: b907d978-68be-4364-8db4-aa48e940f712
  name: kubecamp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000s
  selector:
    app: kubecamp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: b907d978-68be-4364-8db4-aa48e940f712
  name: kubecamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecamp
  template:
    metadata:
      labels:
        app: kubecamp
        app.kubernetes.io/managed-by: skaffold
        skaffold.dev/run-id: b907d978-68be-4364-8db4-aa48e940f712
    spec:
      containers:
      - env:
        - name: ENABLE_FEATURE
          valueFrom:
            configMapKeyRef:
              key: ENABLE_FEATURE
              name: fancy-features-gtgb94tk65
        image: gcr.io/agmsb-k8s/kubecamp-app:3d757c4@sha256:7735454dcf1f64c728b25f5c8d8e08cbe20127d8036cef6087ae3ed7571c9ff7
        imagePullPolicy: IfNotPresent
        name: kubecamp-app
        ports:
        - containerPort: 5000
