apiVersion: v1
data:
  ENABLE_FEATURE: the stable feature that belongs in prod
kind: ConfigMap
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 8b7416db-aa7b-4223-b025-36a561639ab3
  name: fancy-features-gtgb94tk65
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 8b7416db-aa7b-4223-b025-36a561639ab3
  name: kubecamp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: kubecamp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 8b7416db-aa7b-4223-b025-36a561639ab3
  name: kubecamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecamp
  template:
    metadata:
      labels:
        app: kubecamp
        app.kubernetes.io/managed-by: skaffold
        skaffold.dev/run-id: 8b7416db-aa7b-4223-b025-36a561639ab3
    spec:
      containers:
      - env:
        - name: ENABLE_FEATURE
          valueFrom:
            configMapKeyRef:
              key: ENABLE_FEATURE
              name: fancy-features-gtgb94tk65
        image: gcr.io/agmsb-k8s/kubecamp-app:0172be3@sha256:08a29b01cab7ce7dcefb0012e4ec90a2a4d34c4ccdd68e2e11f2088146865dea
        imagePullPolicy: IfNotPresent
        name: kubecamp-app
        ports:
        - containerPort: 5000
