apiVersion: v1
data:
  ENABLE_FEATURE: the stable feature that belongs in prod
kind: ConfigMap
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: bfbf14b7-6c29-46d5-a875-7d384fa843e4
  name: fancy-features-gtgb94tk65
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: bfbf14b7-6c29-46d5-a875-7d384fa843e4
  name: kubecamp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: kubecamp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: bfbf14b7-6c29-46d5-a875-7d384fa843e4
  name: kubecamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecamp
  template:
    metadata:
      labels:
        app: kubecamp
        app.kubernetes.io/managed-by: skaffold
        skaffold.dev/run-id: bfbf14b7-6c29-46d5-a875-7d384fa843e4
    spec:
      containers:
      - env:
        - name: ENABLE_FEATURE
          valueFrom:
            configMapKeyRef:
              key: ENABLE_FEATURE
              name: fancy-features-gtgb94tk65
        image: gcr.io/agmsb-k8s/kubecamp-app:e823dff@sha256:2f534617e3af0c8663bc05a914bb2ccd241266809c7fdd0964d7ed70677ab4bf
        imagePullPolicy: IfNotPresent
        name: kubecamp-app
        ports:
        - containerPort: 5000
