apiVersion: v1
data:
  ENABLE_FEATURE: the stable feature that belongs in prod
kind: ConfigMap
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 088aeb79-6d90-4155-a5ca-db9b9a9470c1
  name: fancy-features-gtgb94tk65
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 088aeb79-6d90-4155-a5ca-db9b9a9470c1
  name: kubecamp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: kubecamp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubecamp
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 088aeb79-6d90-4155-a5ca-db9b9a9470c1
  name: kubecamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecamp
  template:
    metadata:
      labels:
        app: kubecamp
        app.kubernetes.io/managed-by: skaffold
        skaffold.dev/run-id: 088aeb79-6d90-4155-a5ca-db9b9a9470c1
    spec:
      containers:
      - env:
        - name: ENABLE_FEATURE
          valueFrom:
            configMapKeyRef:
              key: ENABLE_FEATURE
              name: fancy-features-gtgb94tk65
        image: gcr.io/agmsb-k8s/kubecamp-app:9c87608@sha256:cbd7b66961cb22990adba3f466559decc33a7b9accfec0d1ca67a55e7ea1392d
        imagePullPolicy: IfNotPresent
        name: kubecamp-app
        ports:
        - containerPort: 5000
